version: "3"
services:
  api:
    restart: on-failure
    build: .
    depends_on:
      - postgres
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    ports:
      - "80:5000"
    volumes:
      - .:/app/

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:    
      - ./data:/data
volumes:
  data: